### PR TITLE
Change ALL the things!

### PR DESCRIPTION
**Pull request by boennemann**

### CODE REVIEW

**Comment by boennemann** [comment]
[clabot:check]

**Comment by boennemann** [comment]
[clabot:check=davidpfahler]

**Comment by boennemann** [comment]
[clabot:check=cubiq]

**Comment by cubiq** [comment]
[clabot:check]

**Comment by goeddea** [comment]
[clabot:check]

**Comment by goeddea** [comment]
[clabot:check=goeddea]

**Comment by goeddea** [comment]
[clabot:check]

**Comment by davidpfahler** [comment]
[clabot:check]

**Comment by imlucas** [comment]
[clabot:check=imlucas]

**Comment by ferventcoder** [comment]
[clabot:check=ferventcoder]

**Comment by robinzimmermann** [comment]
[clabot:check=robinzimmermann]

**Comment by arcestia** [comment]
[clabot:check]

**Comment by devarshi112** [comment]
[clabot:check]

**Comment by hirenoble** [comment]
[clabot:check]

**Pull request closed without merging**
